### ISSUE TITLE
Deployment issue, npm start not found.

### ISSUE THREAD

**Issue by facultymatt** [ericclemmons/genesis-skeleton#60]
Hello all,

I tried deploying this morning and its failing. I get the following logs from Heroku: 

```
2013-01-28T18:05:25+00:00 heroku[web.1]: Starting process with command `npm start`
2013-01-28T18:05:25+00:00 app[web.1]: bash: npm: command not found
2013-01-28T18:05:26+00:00 heroku[web.1]: Process exited with status 127
2013-01-28T18:05:26+00:00 heroku[web.1]: State changed from starting to crashed
```

Any thoughts? 

Also, while deploying I began pondering how this works with heroku... In the past I have always deployed simple heroku node apps, make 1 or 2 JS files. With the genesis setup: 
- How does Heroku know to run code from the dist folder?
- Does Heroku even run from the dist folder, since the actual node server is never copied over from the src folder. 

Thanks all, keep up the great work!

**Comment by ericclemmons** [comment]
When heroku deploys, it runs the `Procfile`, which in turn calls `npm start`, which in turn runs the script:

```
./node_modules/.bin/grunt build && node src/server/server
```

You can test it out using `foreman`, which comes with the Heroku toolbelt.  Perhaps I should modify the `Procfile` to run the above command explicitly?

**Comment by facultymatt** [comment]
@ericclemmons thanks for the explanation. Running `foreman start` successfully executes the start command (building and starting the server).

I tried adding the command directly in the `Procfile` and while this works, the app still doesn't start successfully. I get the following error logs from Heroku: 

`
2013-01-28T23:04:47+00:00 app[web.1]: Running "copy:bootstrap" (copy) task
2013-01-28T23:04:47+00:00 app[web.1]: Copying files to /app/dist/img/...OK
2013-01-28T23:04:47+00:00 app[web.1]: Running "copy:components" (copy) task
2013-01-28T23:04:47+00:00 app[web.1]: 
2013-01-28T23:04:47+00:00 app[web.1]: Copying files to /app/dist/components/...OK
2013-01-28T23:04:47+00:00 app[web.1]: 
2013-01-28T23:04:47+00:00 app[web.1]: Copying files to /app/dist/...OK
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:346:11)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:346:11)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Object.module.exports (/app/node_modules/grunt-usemin/tasks/usemin.js:107:24)
2013-01-28T23:04:47+00:00 app[web.1]: Running "copy:public" (copy) task
2013-01-28T23:04:47+00:00 app[web.1]: Running "useminPrepare:html" (useminPrepare) task
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:319:9)
2013-01-28T23:04:47+00:00 app[web.1]: <WARN> Error compiling LESS. Use --force to continue. </WARN>
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:346:11)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Object.task.registerTask.thisTask.fn (/app/node_modules/grunt/lib/grunt/task.js:58:16)
2013-01-28T23:04:47+00:00 app[web.1]: >> TypeError: Object #<Object> has no method 'options'
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Object.task.registerMultiTask.thisTask (/app/node_modules/grunt/lib/grunt/task.js:109:15)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:319:9)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:343:36)
2013-01-28T23:04:47+00:00 app[web.1]: >>     at Task.<anonymous> (/app/node_modules/grunt/lib/util/task.js:319:9)
2013-01-28T23:04:47+00:00 app[web.1]: 
2013-01-28T23:04:47+00:00 app[web.1]: Aborted due to warnings.
`

Note the build is successfully locally running `grunt server` and `grunt build` and also with `foreman start` -- so I'm at a loss as to where these Less errors are coming from.

Have you successfully deployed the most recent build of genesis to heroku or am I running into isolated issues on my end?

**Comment by facultymatt** [comment]
Looking into this more... seems that the Procfile script is getting run when a user first hits the site? In other words, the git push and build works, but then one I visit the site to preview it the system tries to build again (or at least compile less) and fails.

**Comment by ericclemmons** [comment]
I'll try this on my end and resolve it for you!  `master` has been volatile as the guide is being put in and final architecture decisions are made.

**Comment by gavinjpotts** [comment]
I had this issue when deploying to Heroku - fixed it by adding Bower as a dependency in package.json. Also had to add a Procfile to make it work with Heroku.

**Comment by ericclemmons** [comment]
Well, then I made a mistake by removing the `Procfile`.  (I assumed a Heroku deployment to be presumptuous)
- [ ] Add back in Procfile
- [ ] Correct `package.json` with necessary dependencies (e.g. Bower, etc.) for deployment

**Comment by facultymatt** [comment]
Haven't tested this yet, but how does it work having Bower installed both locally and globally?

**Comment by gavinjpotts** [comment]
You might be right about the Procfile being presumptuous - I think my mistake was following the Heroku instructions on the Genesis homepage verbatim. Maybe a more appropriate fix would be to mention that step in the heroku instructions instead of making it a part of the repository?

**Comment by ericclemmons** [comment]
You're right.  The docs need to seriously be updated after the significant changes we've made recently to structure and whatnot.

On the flip side, if Heroku is, like it was for me, a common choice 1st-time deployers, a Procfile adds ~20 characters to the repo.

I didn't have the issue @facultygavin has because Bower is installed globally for me, but I'll take care of this & get it playing nice with Heroku again!

**Comment by ericclemmons** [comment]
@kwhitley had the same problem as you, so I'll be adding the Procfile back in for 1st-class Heroku support...

**Comment by ericclemmons** [comment]
Test out `master`.  I added back the `Procfile`, and if you remove `build` from `.gitignore` and commit it, Nodejitsu works as well.
