### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by kwhitley** [ericclemmons/genesis-skeleton#73]
```
Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "express-server" task

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at Function.app.listen (/Users/kevinwhitley/Sites/status-board/node_modules/express/lib/application.js:529:24)
    at Object.<anonymous> (/Users/kevinwhitley/Sites/status-board/src/server/server.js:3:22)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

This happens... the server appears to continue through it, but won't serve routes, etc.

**Comment by kwhitley** [comment]
@ericclemmons There you go!

**Comment by ericclemmons** [comment]
Crap, I'm having a hard time replicating this without starting two `grunt server`s in two tabs, but that's expected to fail.

**Comment by ericclemmons** [comment]
Found out how to repeat it!
1. `grunt server` (works)
2. Cause `jshint` error via some bad JS (server fails)
3. Fix previous error
4. `grunt server` (fails)
5. Refresh webpage in browser (timesout/fails)
6. `grunt server` (works)

So either `jshint` should be ran in parallel or perhaps the server should be ran 1st instead.
